if(!window.TypekitPreview)window.TypekitPreview={};window.TypekitPreview.config={"pi":"//use.typekit.net/c/{id}/{description}/{format}{/extras*}?{token}","pk":"//use.typekit.net/p/{id}/{description}/{format}{/extras*}?{token}"};
/*{"k":"1.6.5","version":"1.0","created":"2013-11-07T12:43:39Z"}*/
;(function(window,document,undefined){
var j=!0,l=null,m=!1;function p(a){return function(){return this[a]}}var aa=this;function ba(a,b){var c=a.split("."),d=aa;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&void 0!==b?d[e]=b:d=d[e]?d[e]:d[e]={}}function ca(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function q(a,b,c){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:fa;return q.apply(l,arguments)}var ga=Date.now||function(){return+new Date};
function ha(a,b){this.ea=a;this.S=b||a;this.K=this.S.document}ha.prototype.createElement=function(a,b,c){a=this.K.createElement(a);if(b)for(var d in b)b.hasOwnProperty(d)&&("style"==d?a.style.cssText=b[d]:a.setAttribute(d,b[d]));c&&a.appendChild(this.K.createTextNode(c));return a};function ia(a,b,c){a=a.K.getElementsByTagName(b)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(c,a.lastChild)}
function r(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return;c.push(b);a.className=c.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function t(a,b){for(var c=a.className.split(/\s+/),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function ja(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return j;return m}
function ka(a){var b=a.S.location.protocol;"about:"==b&&(b=a.ea.location.protocol);return"https:"==b?"https:":"http:"}function u(a,b,c){this.Ka=a;this.V=b;this.Ja=c}ba("webfont.BrowserInfo",u);u.prototype.ua=p("Ka");u.prototype.hasWebFontSupport=u.prototype.ua;u.prototype.va=p("V");u.prototype.hasWebKitFallbackBug=u.prototype.va;u.prototype.wa=p("Ja");u.prototype.hasWebKitMetricsBug=u.prototype.wa;function v(a,b,c,d){this.e=a!=l?a:l;this.m=b!=l?b:l;this.B=c!=l?c:l;this.h=d!=l?d:l}var la=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;
function w(a,b){return a.e>b.e||a.e===b.e&&a.m>b.m||a.e===b.e&&a.m===b.m&&a.B>b.B?1:a.e<b.e||a.e===b.e&&a.m<b.m||a.e===b.e&&a.m===b.m&&a.B<b.B?-1:0}function x(a,b){return 0===w(a,b)||1===w(a,b)}v.prototype.toString=function(){return[this.e,this.m||"",this.B||"",this.h||""].join("")};
function y(a){a=la.exec(a);var b=l,c=l,d=l,e=l;a&&(a[1]!==l&&a[1]&&(b=parseInt(a[1],10)),a[2]!==l&&a[2]&&(c=parseInt(a[2],10)),a[3]!==l&&a[3]&&(d=parseInt(a[3],10)),a[4]!==l&&a[4]&&(e=/^[0-9]+$/.test(a[4])?parseInt(a[4],10):a[4]));return new v(b,c,d,e)}function z(a,b,c,d,e,f,g,h,k,n,s){this.M=a;this.o=b;this.Ia=c;this.t=d;this.z=e;this.ka=f;this.k=g;this.g=h;this.Ba=k;this.J=n;this.s=s}ba("webfont.UserAgent",z);z.prototype.getName=p("M");z.prototype.getName=z.prototype.getName;z.prototype.ta=p("Ia");
z.prototype.getVersion=z.prototype.ta;z.prototype.pa=p("t");z.prototype.getEngine=z.prototype.pa;z.prototype.qa=p("ka");z.prototype.getEngineVersion=z.prototype.qa;z.prototype.ra=p("k");z.prototype.getPlatform=z.prototype.ra;z.prototype.sa=p("Ba");z.prototype.getPlatformVersion=z.prototype.sa;z.prototype.oa=p("J");z.prototype.getDocumentMode=z.prototype.oa;z.prototype.na=p("s");z.prototype.getBrowserInfo=z.prototype.na;function ma(a,b){this.c=a;this.I=b}
var na=new z("Unknown",new v,"Unknown","Unknown",new v,"Unknown","Unknown",new v,"Unknown",void 0,new u(m,m,m));
ma.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE")||-1!=this.c.indexOf("Trident/")){a=A(this);var b=B(this),c=y(b),d=l,e=l,f=l,g=l,h=C(this.c,/Trident\/([\d\w\.]+)/,1),k=D(this.I),d=-1!=this.c.indexOf("MSIE")?C(this.c,/MSIE ([\d\w\.]+)/,1):C(this.c,/rv:([\d\w\.]+)/,1),e=y(d);""!=h?(f="Trident",g=y(h)):(f="Unknown",g=new v,h="Unknown");a=new z("MSIE",e,d,f,g,h,a,c,b,k,new u("Windows"==a&&6<=e.e||"Windows Phone"==a&&8<=c.e,m,m))}else if(-1!=this.c.indexOf("Opera"))a:if(a="Unknown",b=
C(this.c,/Presto\/([\d\w\.]+)/,1),c=y(b),d=B(this),e=y(d),f=D(this.I),c.e!==l?a="Presto":(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=C(this.c,/rv:([^\)]+)/,1),c=y(b)),-1!=this.c.indexOf("Opera Mini/"))g=C(this.c,/Opera Mini\/([\d\.]+)/,1),h=y(g),a=new z("OperaMini",h,g,a,c,b,A(this),e,d,f,new u(m,m,m));else{if(-1!=this.c.indexOf("Version/")&&(g=C(this.c,/Version\/([\d\.]+)/,1),h=y(g),h.e!==l)){a=new z("Opera",h,g,a,c,b,A(this),e,d,f,new u(10<=h.e,m,m));break a}g=C(this.c,/Opera[\/ ]([\d\.]+)/,1);
h=y(g);a=h.e!==l?new z("Opera",h,g,a,c,b,A(this),e,d,f,new u(10<=h.e,m,m)):new z("Opera",new v,"Unknown",a,c,b,A(this),e,d,f,new u(m,m,m))}else/OPR\/[\d.]+/.test(this.c)?a=oa(this):/AppleWeb(K|k)it/.test(this.c)?a=oa(this):-1!=this.c.indexOf("Gecko")?(a="Unknown",b=new v,c="Unknown",d=B(this),e=y(d),f=m,-1!=this.c.indexOf("Firefox")?(a="Firefox",c=C(this.c,/Firefox\/([\d\w\.]+)/,1),b=y(c),f=3<=b.e&&5<=b.m):-1!=this.c.indexOf("Mozilla")&&(a="Mozilla"),g=C(this.c,/rv:([^\)]+)/,1),h=y(g),f||(f=1<h.e||
1==h.e&&9<h.m||1==h.e&&9==h.m&&2<=h.B||g.match(/1\.9\.1b[123]/)!=l||g.match(/1\.9\.1\.[\d\.]+/)!=l),a=new z(a,b,c,"Gecko",h,g,A(this),e,d,D(this.I),new u(f,m,m))):a=na;return a};function A(a){var b=C(a.c,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=C(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function B(a){var b=C(a.c,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b||(b=C(a.c,/Windows Phone( OS)? ([^;)]+)/,2))||(b=C(a.c,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=C(a.c,/(?:Linux|CrOS) ([^;)]+)/,1))for(var b=b.split(/\s/),c=0;c<b.length;c+=1)if(/^[\d\._]+$/.test(b[c]))return b[c];return(a=C(a.c,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function oa(a){var b=A(a),c=B(a),d=y(c),e=C(a.c,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1),f=y(e),g="Unknown",h=new v,k="Unknown",n=m;/OPR\/[\d.]+/.test(a.c)?g="Opera":-1!=a.c.indexOf("Chrome")||-1!=a.c.indexOf("CrMo")||-1!=a.c.indexOf("CriOS")?g="Chrome":/Silk\/\d/.test(a.c)?g="Silk":"BlackBerry"==b||"Android"==b?g="BuiltinBrowser":-1!=a.c.indexOf("PhantomJS")?g="PhantomJS":-1!=a.c.indexOf("Safari")?g="Safari":-1!=a.c.indexOf("AdobeAIR")&&(g="AdobeAIR");"BuiltinBrowser"==g?k="Unknown":"Silk"==g?k=C(a.c,
/Silk\/([\d\._]+)/,1):"Chrome"==g?k=C(a.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.c.indexOf("Version/")?k=C(a.c,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==g?k=C(a.c,/AdobeAIR\/([\d\.]+)/,1):"Opera"==g?k=C(a.c,/OPR\/([\d.]+)/,1):"PhantomJS"==g&&(k=C(a.c,/PhantomJS\/([\d.]+)/,1));h=y(k);n="AdobeAIR"==g?2<h.e||2==h.e&&5<=h.m:"BlackBerry"==b?10<=d.e:"Android"==b?2<d.e||2==d.e&&1<d.m:526<=f.e||525<=f.e&&13<=f.m;return new z(g,h,k,"AppleWebKit",f,e,b,d,c,D(a.I),new u(n,536>f.e||536==f.e&&11>f.m,"iPhone"==
b||"iPad"==b||"iPod"==b||"Macintosh"==b))}function C(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""}function D(a){if(a.documentMode)return a.documentMode}function pa(a){this.Aa=a||"-"}pa.prototype.h=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.Aa)};function qa(a,b,c){this.j=a;this.l=b;this.O=c;this.q="wf";this.p=new pa("-")}
function E(a){t(a.l,a.p.h(a.q,"loading"));ja(a.l,a.p.h(a.q,"active"))||r(a.l,a.p.h(a.q,"inactive"));F(a,"inactive")}function F(a,b,c){if(a.O[b])if(c)a.O[b](c.getName(),G(c));else a.O[b]()}function H(a,b){this.M=a;this.W=4;this.N="n";var c=(b||"n4").match(/^([nio])([1-9])$/i);c&&(this.N=c[1],this.W=parseInt(c[2],10))}H.prototype.getName=p("M");function G(a){return a.N+a.W}function I(a,b){this.j=a;this.F=b;this.w=this.j.createElement("span",{"aria-hidden":"true"},this.F)}
function J(a,b){var c;c=[];for(var d=b.M.split(/,\s*/),e=0;e<d.length;e++){var f=d[e].replace(/['"]/g,"");-1==f.indexOf(" ")?c.push(f):c.push("'"+f+"'")}c=c.join(",");d="normal";e=b.W+"00";"o"===b.N?d="oblique":"i"===b.N&&(d="italic");a.w.style.cssText="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+c+";"+("font-style:"+d+";font-weight:"+e+";")}
function K(a){ia(a.j,"body",a.w)}I.prototype.remove=function(){var a=this.w;a.parentNode&&a.parentNode.removeChild(a)};function ra(a,b,c,d,e,f,g,h){this.X=a;this.ya=b;this.j=c;this.v=d;this.F=h||"BESbswy";this.s=e;this.G={};this.T=f||5E3;this.fa=g||l;this.D=this.C=l;a=new I(this.j,this.F);K(a);for(var k in L)L.hasOwnProperty(k)&&(J(a,new H(L[k],G(this.v))),this.G[L[k]]=a.w.offsetWidth);a.remove()}var L={Ra:"serif",Qa:"sans-serif",Na:"monospace"};
ra.prototype.start=function(){this.C=new I(this.j,this.F);K(this.C);this.D=new I(this.j,this.F);K(this.D);this.Fa=ga();J(this.C,new H(this.v.getName()+",serif",G(this.v)));J(this.D,new H(this.v.getName()+",sans-serif",G(this.v)));sa(this)};function ta(a,b,c){for(var d in L)if(L.hasOwnProperty(d)&&b===a.G[L[d]]&&c===a.G[L[d]])return j;return m}
function sa(a){var b=a.C.w.offsetWidth,c=a.D.w.offsetWidth;b===a.G.serif&&c===a.G["sans-serif"]||a.s.V&&ta(a,b,c)?ga()-a.Fa>=a.T?a.s.V&&ta(a,b,c)&&(a.fa===l||a.fa.hasOwnProperty(a.v.getName()))?N(a,a.X):N(a,a.ya):setTimeout(q(function(){sa(this)},a),25):N(a,a.X)}function N(a,b){a.C.remove();a.D.remove();b(a.v)}function O(a,b,c,d){this.j=b;this.A=c;this.P=0;this.ha=this.da=m;this.T=d;this.s=a.s}
O.prototype.U=function(a,b,c,d){if(0===a.length&&d)E(this.A);else{this.P+=a.length;d&&(this.da=d);for(d=0;d<a.length;d++){var e=a[d],f=b[e.getName()],g=this.A,h=e;r(g.l,g.p.h(g.q,h.getName(),G(h).toString(),"loading"));F(g,"fontloading",h);(new ra(q(this.la,this),q(this.ma,this),this.j,e,this.s,this.T,c,f)).start()}}};
O.prototype.la=function(a){var b=this.A;t(b.l,b.p.h(b.q,a.getName(),G(a).toString(),"loading"));t(b.l,b.p.h(b.q,a.getName(),G(a).toString(),"inactive"));r(b.l,b.p.h(b.q,a.getName(),G(a).toString(),"active"));F(b,"fontactive",a);this.ha=j;ua(this)};O.prototype.ma=function(a){var b=this.A;t(b.l,b.p.h(b.q,a.getName(),G(a).toString(),"loading"));ja(b.l,b.p.h(b.q,a.getName(),G(a).toString(),"active"))||r(b.l,b.p.h(b.q,a.getName(),G(a).toString(),"inactive"));F(b,"fontinactive",a);ua(this)};
function ua(a){0==--a.P&&a.da&&(a.ha?(a=a.A,t(a.l,a.p.h(a.q,"loading")),t(a.l,a.p.h(a.q,"inactive")),r(a.l,a.p.h(a.q,"active")),F(a,"active")):E(a.A))}function P(a){this.j=a}P.prototype.toString=function(){return encodeURIComponent(this.j.S.location.hostname||this.j.ea.location.hostname)};function va(a,b){this.n=a;this.aa=b}
va.prototype.toString=function(){for(var a=[],b=0;b<this.aa.length;b++)for(var c=this.aa[b],d=c.r(),c=c.r(this.n),e=0;e<d.length;e++){var f;a:{for(f=0;f<c.length;f++)if(d[e]===c[f]){f=j;break a}f=m}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");b=[];for(d=a.length;0<d;d-=4)c=a.slice(0>d-4?0:d-4,d),b.unshift(parseInt(c,2).toString(16));return b.join("")};function Q(a){this.Ha=a}
Q.prototype.h=function(a,b){var c=b||{},d=this.Ha.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,d){return d&&c[b]?"/"+c[b].join("/"):c[b]||""});d.match(/^\/\//)&&(d=(a?"https:":"http:")+d);return d.replace(/\/*\?*($|\?)/,"$1")};function wa(a,b,c,d,e){for(var f=[],g=0;g<d.length;g++)f.push(d[g].toString());c={format:c,extras:f};c.id=a;c.description=b;e&&(c.token=e);return c}function R(a,b,c,d){this.u=a;this.L=b;this.xa=c;this.Ga=d;this.ca={};this.Q={}}
R.prototype.r=function(a){return a?(this.ca[a]||this.L).slice(0):this.L.slice(0)};function xa(a,b,c){for(var d=[],e=a.u.split(",")[0].replace(/"|'/g,""),f=a.r(),g,h=[],k={},n=0;n<f.length;n++)g=f[n],0<g.length&&!k[g]&&(k[g]=j,h.push(g));c=c.ga?c.ga(e,h,d):h;a.ca[b]=c;a.Q[b]=d}R.prototype.U=function(a,b,c){var d=[],e={};d.push(this.u);e[this.u]=this.r(b);b=this.Q[b]||[];for(var f=0;f<b.length;f++){for(var g=b[f],h=g.u,k=m,n=0;n<d.length;n++)d[n]==h&&(k=j);k||(d.push(h),e[h]=g.r())}a(d,e,c)};
function ya(a,b){this.u=a;this.L=b}ya.prototype.r=p("L");function za(){this.ja=this.La=this.H=this.R=this.za=j}function S(a){return"Windows"===a.k}function T(a){return S(a)&&0===w(a.g,new v(5,1))||S(a)&&0===w(a.g,new v(5,2))||S(a)&&0===w(a.g,new v(6,0))||S(a)&&x(a.g,new v(6,1))}function U(a){return"Macintosh"===a.k&&(x(a.g,new v(10,4))||a.g.e===l)}function Aa(a,b){return b.za&&("iPhone"===a.k||"iPod"===a.k)}function Ba(a,b){return Aa(a,b)&&x(a.g,new v(4,2))&&-1===w(a.g,new v(5))}
function Ca(a,b){return b.R&&"iPad"===a.k&&x(a.g,new v(4,2))&&-1===w(a.g,new v(5))}function V(a,b){return b.H&&"Android"===a.k}function Da(a,b){return V(a,b)&&x(a.g,new v(2,2))&&-1===w(a.g,new v(3,1))}function Ea(a,b){return V(a,b)&&x(a.g,new v(3,1))&&-1===w(a.g,new v(4,1))}function W(a){return"Linux"===a.k||"Ubuntu"===a.k}function Fa(a){return"Gecko"===a.t&&0===w(a.z,new v(1,9,1))&&!/^b[1-3]$/.test(a.z.h||"")}
function Ga(a){return"Safari"===a.getName()&&"AppleWebKit"===a.t||"Unknown"===a.getName()&&"AppleWebKit"===a.t&&("iPhone"===a.k||"iPad"===a.k||"iPod"===a.k)}function Ha(a){return"Safari"===a.getName()&&"AppleWebKit"===a.t&&x(a.z,new v(525,13))&&-1===w(a.z,new v(534,50))}function Ia(a){return"Opera"===a.getName()&&x(a.o,new v(10,54))&&-1===w(a.o,new v(11,10))}function Ja(a){return"BuiltinBrowser"===a.getName()}function Ka(a){this.ga=a}function La(a,b){return b}
var Ma={Oa:"a",Pa:"b",Ta:"d",Sa:"f",Ma:"i"},Na={a:function(a,b){return Ha(a)&&T(a)||Ja(a)&&(Da(a,b)||V(a,b)&&x(a.g,new v(4,1)))||b.H&&"Silk"===a.getName()&&-1===w(a.o,new v(2))&&(Da(a,b)||U)||b.H&&"Silk"===a.getName()&&x(a.o,new v(2))&&V(a,b)&&x(a.g,new v(4,1))||Ga(a)&&(Ca(a,b)||Ba(a,b))||Fa(a)&&(T(a)||W(a))||Ia(a)&&(T(a)||W(a))||("Chrome"===a.getName()&&1===w(a.o,new v(4,0,249))&&-1===w(a.o,new v(6))||0===w(a.o,new v(4,0,249))&&(a.o.h===l||4<=a.o.h))&&(T(a)||W(a)||U(a))||"Chrome"===a.getName()&&
x(a.o,new v(6))&&(Ca(a,b)||Ba(a,b))||"AdobeAIR"===a.getName()&&x(a.o,new v(2,5))&&(S(a)&&a.g.e===l||W(a))},b:function(a){return Fa(a)&&U(a)||Ha(a)&&U(a)||Ia(a)&&U(a)||"AdobeAIR"===a.getName()&&x(a.o,new v(2,5))&&U(a)},d:function(a,b){return"Chrome"===a.getName()&&x(a.o,new v(6))&&(T(a)||W(a)||U(a)||V(a,b)||"CrOS"===a.k||b.R&&"iPad"===a.k&&x(a.g,new v(5))||Aa(a,b)&&x(a.g,new v(5)))||"Gecko"===a.t&&1===w(a.z,new v(1,9,1))&&(T(a)||W(a)||U(a)||V(a,b))||"Safari"===a.getName()&&("AppleWebKit"===a.t&&x(a.z,
new v(534,50)))&&(T(a)||U(a))||Ga(a)&&(b.R&&"iPad"===a.k&&x(a.g,new v(5))||Aa(a,b)&&x(a.g,new v(5)))||"Opera"===a.getName()&&x(a.o,new v(11,10))&&(T(a)||W(a)||U(a)||V(a,b))||"MSIE"===a.getName()&&9<=a.J&&(S(a)&&x(a.g,new v(6,1))||S(a)&&0===w(a.g,new v(6,0)))||"MSIE"===a.getName()&&b.La&&"Windows Phone"===a.k&&x(a.g,new v(8))||Ja(a)&&b.ja&&"BlackBerry"===a.k&&x(a.g,new v(10))},f:function(a,b){return Ja(a)&&Ea(a,b)||b.H&&"Silk"===a.getName()&&x(a.o,new v(2))&&(Ea(a,b)||W(a))},i:function(a){return"MSIE"===
a.getName()&&(x(a.o,new v(6,0))&&(void 0===a.J||9>a.J))&&T(a)}},Oa={};
Oa.i=new Ka(function(a,b,c){for(var d=0;d<b.length;d+=1){var e=b[d],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+e;c.push(new ya(f,[e]))}a={};for(e=0;e<b.length;e++)c=b[e],d=c.charAt(1),(a[d]||(a[d]=[])).push(c);c=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(e=0;e<c.length;e++)for(var f=c[e],g=0;g<f.length;g++){var h=f[g];if(a[h]){d=d.concat(a[h]);break}}c=d;d={};a=[];for(e=0;e<c.length;e++)f=c[e],d[f]||(d[f]=j,a.push(f));c=[];for(d=0;d<b.length;d++){e=b[d];for(f=0;f<a.length;f++)g=a[f],g==e&&
c.push(g)}return c});var X={};X.a=X.b=X.d=function(){return[]};X.f=function(a){return[new P(a)]};X.i=function(a,b,c){return[new P(a),new va(b,c)]};var Pa={all:1,"default":2};function Y(a,b,c,d,e,f,g){this.Da=a;this.Ca=b;this.n=c;this.ba=d;this.j=e;this.c=f;this.l=g;this.Y="anonymous";this.Z=l;this.$="default"}Y.prototype.Ea=function(a){var b=a.auth_id;b&&(this.Y=b);if(b=a.auth_token)this.Z=b;if((a=a.default_subset)&&Pa[a])this.$=a};
Y.prototype.load=function(a,b){for(var c=b||{},d=a,e=[],f=0;f<d.length;f++){var g=/^[A-Za-z0-9_-]+$/,h=d[f],k=h.id,n=h.variations,s=h.css_name,s=s&&"string"==typeof s&&s.match(g)?s:k,h=h.subset,h=Pa[h]?h:this.$;if("string"==typeof k&&k.match(g)&&"object"==typeof n&&0<n.length){for(var g={},da=[],ea=0;ea<n.length;ea++){var M=n[ea];M&&(0<M.length&&!g[M])&&(da.push(M),g[M]=j)}0<da.length&&e.push(Qa(k,da.sort(),s,h))}}e=a=e.sort(function(a,b){var c=a.css_name,d=b.css_name;return c<d?-1:c>d?1:0});d=[];
for(f=0;f<e.length;f++)k=e[f],d.push(new R(k.css_name,k.variations,k.id,k.subset));e=l;if(this.n){for(e=0;e<d.length;e++)xa(d[e],this.n,this.ba);e=a;f=[];k=[];for(n=0;n<e.length;n++)s=e[n],h=Pa[s.subset],f.push(s.css_name+":"+s.variations.join(":")),k.push(s.id+":"+h);e=0<f.length?[f.join(","),k.join(",")].join("."):"";f=X[this.n](this.j,this.n,d);e=wa(this.Y,e,this.n,f,this.Z||void 0);e=this.Da.h("https:"===ka(this.j),e)}if(Ra(this,d,e,c)){c=[];for(e=0;e<d.length;e++){n=d[e];s=n.r(this.n);f=n.xa;
k=n.Ga;0<s.length&&c.push(Qa(f,s,n.u,k));n=n.Q[this.n]||[];for(s=0;s<n.length;s++)h=n[s],c.push(Qa(f,h.r(),h.u,k))}}else c=[];return c};
function Ra(a,b,c,d){d=new qa(a.j,a.l,d||{});if(a.n){if(b.length){var e=new O(a.c,a.j,d),f=function(a,b,c){for(var d=[],f=0;f<a.length;f+=1){var g=a[f];if(b[g])for(var h=b[g],k=0;k<h.length;k+=1)d.push(new H(g,h[k]));else d.push(new H(g))}e.U(d,{},l,c)};r(d.l,d.p.h(d.q,"loading"));F(d,"loading");d=a.j;c=d.createElement("link",{rel:"stylesheet",href:c});var g=m;c.onload=function(){g||(g=j)};c.onerror=function(){g||(g=j)};ia(d,"head",c);var h=a.n,k=a.j,n=function(){if(k.K.body)for(var a=0;a<b.length;a++)b[a].U(f,
h,a==b.length-1);else setTimeout(n,0)};n()}}else return E(d),m;return j}Y.prototype.ia=function(a,b,c,d){d=d||{};for(var e=[],f=b.split(".")[0].split(","),g=0;g<f.length;g++){var h=f[g].split(":"),k=h[0],h=h.slice(1);0<k.length&&e.push(new R(k,h))}f=l;if(this.n){for(f=0;f<e.length;f++)xa(e[f],this.n,this.ba);f=X[this.n](this.j,this.n,e);a=wa(a,b,this.n,f,c);f=this.Ca.h("https:"===ka(this.j),a)}Ra(this,e,f,d)};function Qa(a,b,c,d){return{id:a,variations:b,css_name:c,subset:d}}
window.TypekitPreview||(window.TypekitPreview={});
if(!window.TypekitPreview.load){var Sa=window.TypekitPreview.config||{},Ta=new Q(Sa.pk),Ua=new Q(Sa.pi),Va=(new ma(navigator.userAgent,document)).parse(),Z;a:{var Wa=new za||new za,Xa;for(Xa in Ma){var Ya=Ma[Xa];if(Na[Ya](Va,Wa)){Z=Ya;break a}}Z=l}var $=new Y(Ta,Ua,Z,Oa[Z]||new Ka(La),new ha(window),Va,document.documentElement);window.TypekitPreview=$;window.TypekitPreview.setup=$.Ea;window.TypekitPreview.load=$.load;window.TypekitPreview._loadInternal=$.ia};
})(this,document);
